/* eslint-disable */
/**
 * AUTO-GENERATED FILE — do not edit by hand.
 * Generated by: scripts/generate-shopify-campaign-statuses.mjs
 *
 * Source of truth: apps/shopify-api/constants/campaign-status.js
 */

export const SHOPIFY_CAMPAIGN_STATUS_VALUES = [
  'draft',
  'scheduled',
  'sending',
  'paused',
  'completed',
  'failed',
  'cancelled',
  'sent',
] as const;

export type ShopifyCampaignStatus = (typeof SHOPIFY_CAMPAIGN_STATUS_VALUES)[number];

export const SHOPIFY_CAMPAIGN_STATUS_SET: ReadonlySet<string> = new Set(
  SHOPIFY_CAMPAIGN_STATUS_VALUES as readonly string[],
);
